### ISSUE TITLE
Any plans to implemnt QJson printers?

### ISSUE THREAD

**Issue by cezaryece** [fmanlou/qt6printers#1]
I just want to switch from QtCreator to CLion and one of my daily heart pains is lack of pretty look and QJson classes values.

I can understand you can be not interested in this and if so, just give me some instructions how to start with this.
I am quite experienced Qt user, but with C++, not Python. So creating something here is for me quite hard, but I can try...

**Comment by fmanlou** [comment]
Sorry, I haven't been paying much attention to GitHub messages lately. Although I'm not very familiar with Python, I can give it a try.If I have good ideas, I'll share them with you.Thanks for your advice.

**Comment by fmanlou** [comment]
Hello, you can get quick online help for GDB’s Python API from https://sourceware.org/gdb/current/onlinedocs/gdb.html/Python-API.html.

In addition to this, you can check the Qt Creator code to understand how Qt Creator implements the debugging format.
https://github.com/qt-creator/qt-creator/tree/master/share/qtcreator/debugger

I hope it can be helpful to you.

**Comment by fmanlou** [comment]
I have added support for QVariant and QMap. You can review the detailed commit information, and I hope it will be helpful for you.

**Comment by fmanlou** [comment]
I think I don't have time recently to support QJson printers. If I have time later or if I need to debug QJson in vscode, I will add QJson printers then.

**Comment by fmanlou** [comment]
It can support to print QJson now.

**Comment by cezaryece** [comment]
Yes, it supports QJsonObject now. It will be very helpful. Thank you!
